repos:
-   repo: local
    hooks:
    -   id: test-alias-json
        name: Test alias_key.json
        entry: python tests/test_alias_json.py
        language: python
        files: pango_designation/alias_key.json
    -   id: lineages-csv-duplicates
        name: Test lineages.csv for duplicates
        entry: python tests/test_duplicate_designations.py
        language: python
        files: lineages.csv

