name: Analyze lineage notes

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install packages
        run: pip install pandas
      - name: Analyze lineage notes file
        run: python analyze_lineage_notes.py
