name: Analyze lineage notes

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install packages
      run: pip install pandas
    - name: Analyze lineage notes file
      run: python analyze_lineage_notes.py
